version: '3.3'
services:
    mysql:
        container_name: mysql
        ports:
            - '3306:3306'
        volumes:
            - 'db_data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=password
        image: 'mysql:latest'
        restart: always
        networks: 
            - grafana-mysql-flask_app
    flask_app:
        container_name: flask_app
        build: .
        ports:
            - "5001:5000"
        networks: 
            - grafana-mysql-flask_app
        depends_on:
            - mysql
        restart: always
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_HOST=mysql
    grafana:
        environment:
            - GF_LOG_MODE=console
            - GF_LOG_LEVEL=info
        container_name: grafana
        ports:
            - '3001:3000'
        volumes:
            - 'grafana_config:/etc/grafana'
            - 'grafana_data:/var/lib/grafana'
            - 'grafana_logs:/var/log/grafana'
        image: grafana/grafana
        networks: 
            - grafana-mysql-flask_app
        restart: always


networks: 
    grafana-mysql-flask_app:
        name: grafana-mysql-flask_app
volumes:
  grafana_config:
  grafana_data:
  grafana_logs:
  db_data: